prima_app/urls.py
from django.urls import path
from prima_app.views import homepage,welcome,lista,chi_siamo,variabili,index
app_name="prima_app"
urlpatterns=[
    path('homepage', homepage, name='homepage'),
    path('welcome', welcome, name='welcome'),
    path('lista', lista, name='lista'),
    path('chi_siamo', chi_siamo, name='chi_siamo'),
    path('variabili',variabili, name='variabili'),
    path('',index, name='index')
]

primo_progetto/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index_root

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',index_root, name='index_root'),
    path('prima_app/', include("prima_app.urls", namespace="prima_app")),
    path('seconda_app/', include("seconda_app.urls", namespace="seconda_app")),
    path('terza_app/', include("terza_app.urls", namespace="terza_app")),
]

seconda_app/urls.py
from django.urls import path
from seconda_app.views import es_if,if_else_elif,es_for,index
app_name="seconda_app"

urlpatterns=[
    path('es_if',es_if,name='es_if'),
    path('if_else_elif',if_else_elif,name='if_else_elif'),
    path('es_for',es_for,name='es_for'),
    path('', index,name='index')
]

terza_app/urls.py
from django.urls import path
from terza_app.views import diff,pari
app_name="terza_app"
urlpatterns=[
    path('diff', diff, name='diff'),
    path('pari', pari, name='pari'),
     
]

seconda_app/models.py
from django.db import models

# Create your models here.

prima_app/views.py
from django.shortcuts import render
# Create your views here.
def homepage (request):
    return render (request,"prima_app/homepage.html")
def welcome (request):
    return render (request,"prima_app/welcome.html")
def lista (request):
    return render (request,"prima_app/lista.html")
def chi_siamo (request):
    return render (request,"prima_app/chi_siamo.html")

primo_progetto/views.py
from django.shortcuts import render

def index_root(request):
        return render (request,"index_root.html")

seconda_app/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def es_if(request):
    context={
        'var1' :200,
        'var2' :200,
        'var3' :300
    }
    return render (request, "es_if.html", context)
def if_else_elif(request):
    context={
        'var1' :100,
        'var2' :100.0,
        'var3' :100.50,
    }
    return render (request, "if_else_elif.html", context)

def es_for(request):
    context={
        'list1':[1, datetime.date(2019,7,16), 'Do not give up!'],
        'list2':[1, datetime.date(2019,7,16), 'Do not give up!'],
        'my_dict': {'chiave1': 'Valore 1', 'chiave2': 'Valore 2'}

    }
    return render (request, "es_for.html", context)

def index(request):
    return render(request, "seconda_app/index.html")

terza_app/views.py
from django.shortcuts import render


# Create your views here.
def diff(request):
    context={
        'n1' :15,
        'n2' :10,
        'diff': 15-10,
    }
    return render (request, "pari.html", context)
def pari(request):
    context={
        'n1' :15,
        'n2' :10,
         'n3' :16,
        'n4' :17,
         'n5' :18,
        'n6' :19,
         'n7' :1,
        'n8' :2,
         'n9' :3,
        'n10' :4,
         'n11' :5,
        'n12' :6,
         'n13' :7,
        'n14' :8,
         'n15' :9,
        
         
    }
    return render (request, "pari.html", context)
 

prima_app/templates/prima_app/chi_siamo.html
{% extends "base.html"%}
{% block title%} {{block.super}} | Chi siamo {% endblock title%}

{%block content%}
    <h1>Chi siamo</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos ducimus veniam neque repellendus, officia aliquid! Magnam omnis libero harum, aperiam error obcaecati eos, amet alias quo laborum, veniam quam cum.</p>
{%endblock content%}

prima_app/templates/prima_app/homepage.html
{% extends "base.html"%}
{% block title%} {{block.super}} | Homepage {% endblock title%}

{%block content%}
    <h1>Benvenuto</h1>
{%endblock content%}

prima_app/templates/prima_app/index.html
{% extends "base.html"%}
{% block title%} {{block.super}} | Index {% endblock title%}

{%block content%}
    <ol>
        <li><a href="{% url 'prima_app:homepage'%}">Home page benvenuto</a></li>
        <li><a href="{% url 'prima_app:welcome'%}">Welcome</a></li>
        <li><a href="{% url 'prima_app:lista'%}">Lista</a></li>
        <li><a href="{% url 'prima_app:chi_siamo'%}">Chi siamo</a></li>
        <li><a href="{% url 'prima_app:variabili'%}">Variabili</a></li>
    </ol>
{%endblock content%}

prima_app/templates/prima_app/lista.html
{% extends "base.html"%}
{% block title%} {{block.super}} | Lista {% endblock title%}

{%block content%}
  <h1>lista</h1>
  <ol>
    <li>primo</li>
    <li>secondo</li>
    <li>terzo</li>
  </ol>
{%endblock content%}

prima_app/templates/prima_app/variabili.html
{% extends "base.html"%}
{% block title%} {{block.super}} | Variabili {% endblock title%}

{%block content%}
    <ol>
        <li>{{var1}}</li>
        <li>{{var2}}</li>
        <li>{{var3}}</li>
    </ol>
{%endblock content%}

prima_app/templates/prima_app/welcome.html
{% extends "base.html"%}
{% block title%} {{block.super}} | Welcome {% endblock title%}

{%block content%}
    <h1>welcome</h1>
{%endblock content%}

seconda_app/templates/seconda_app/es_for.html
{% extends "base.html"%}
{% block title%} {{block.super}} | Document {% endblock title%}

{%block content%}
    Cicla una sequenza usando <b>forloop.counter</b>
    <br/>
    {% for x in list2 %}
    <i>{{ forloop.counter }} </i>: {{ x }}<br>
    {% endfor %}
    <br/>
    Cicla una sequenza usando <b>forloop.counter0</b>
    <br/>
    {% for x in list2 %}
    <i>{{ forloop.counter0 }}</i>: {{ x }}<br/>
    {% endfor %}
    <br/>
    Stampa il primo elemento della sequenza usando <b>forloop.first</b>:
    <br/>
    {% for x in list2 %}
    {% if forloop.first %}
    <i>Il primo elemento</i> - {{ x }}
    {% endif%}
    {% endfor %}
    <br/>
    Stampa l'ultimo elemento della lista usando <b>forloop.last</b>:
    <br/>
    {% for x in list2 %}
    {% if forloop.last %}
    <i>L'ultimo elemento</i> - {{ x }}
    {% endif%}
    {% endfor %}
    <br/>
    Stampa il numero degli elementi non ancora ciclati usando <b>forloop.revcounter</b>:
    <br/>
    {% for x in list2 %}
    <i>Numero degli elementi da dover ancora ciclare</i> {{ forloop.revcounter }}<br/>
    <i>Elemento</i> {{ x }}<br/>
    {% endfor %}
    <br/>
    Stampa il numero degli elementi non ancora ciclati usando <b>forloop.revcounter0</b>:
    <br/>
    {% for x in list2 %}
    <i>Numero degli elementi da dover ancora ciclare</i> {{ forloop.revcounter0 }}<br/>
    <i>Elemento</i> {{ x }}<br/>
    {% endfor %}
    <br/>
    Stampa la sequenza al contrario usando <b>reversed</b>, attributo del tag <b>for</b>:
    <br/>
    {% for x in list2 reversed %}
    <i>Elemento</i> {{ x }}<br/>
    {% endfor %}

    <h2>Contenuto del dizionario: </h2>   
    <ul>
        {% for key, value in my_dict.items %}
            <li>{{ key }}: {{ value }}</li>
        {% endfor %}
    </ul>
{%endblock content%}

seconda_app/templates/seconda_app/es_if.html
{% extends "base.html"%}
{% block title%} {{block.super}} | es_if {% endblock title%}

{%block content%}
    <b>var1 = {{ var1 }}</b> <br/>
    <b>var2 = {{ var2 }}</b> <br/>
    <b>var3 = {{ var3 }}</b> <br/>
    {% if var1 < var2 %}
        <p><i>var1 è minore di var2 </i></p>
    {% endif %}
    {% if var1 > var2 %}
        <p><i>var1 è maggiore di var2 </i></p>
    {% endif %}
    {% if var1 <= var2 %}
        <p><i>var1 è minore o uguale di var2 </i></p>
    {% endif %}
    {% if var1 >= var2 %}
        <p><i>var1 è maggiore o uguale di var2 </i></p>
    {% endif %}
    {% if var1 == var2 %}
        <p><i>var1 è uguale a var2 </i></p>
    {% endif %}
    {% if var1 != var2 %}
        <p><i>var1 non è uguale a var2 </i></p>
    {% endif %}
    {% if var1 < var2 and var1 < var3 %}
        <p><i>var1 è minore di var2 e var1 è minore di var3 </i></p>
    {% endif %}
    {% if var1 < var2 or var3 < var2 %}
        <p><i>var1 è minore di var2 o var3 è minore di var2 </i></p>
    {% endif %}
    {% if not var1 > var2 %}
        <p><i>var1 non è maggiore di var2 </i></p>
    {% endif %}
{%endblock content%}

seconda_app/templates/seconda_app/if_else_elif.html
{% extends "base.html"%}
{% block title%} {{block.super}} | if_else_elif {% endblock title%}

{%block content%}
    <b>var1 = {{ var1 }} </b> <br/>
    <b>var2 = {{ var2 }}</b> <br/>
    <b>var3 = {{ var3 }}</b> <br/>
    {% if var1 < var2 %}
        <p><i>var1 è minore di var2 </i> </b>
    {% elif var1 > var2 %}
        <p><i>var1 è maggiore di var2 </i></b>
    {% else %}
        <p><i>var1 è uguale a var2 </i></b>
    {% endif %}
    {% if var1 > var2 %}
        <p><i>var1 è maggiore di var2 </i></p>
    {% elif var1 < var2 %}
        <p><i>var1 è minore di var2 </i></p>
    {% else %}
        <p><i>var1 è uguale a var2 </i></b>
    {% endif %}
    {% if var1 <= var2 %}
        <p><i>var1 is minore o uguale di var2 </i></p>
    {% elif var1 > var2 %}
        <p><i>var1 è maggiore di var2 </i> </p>
    {% endif %}
    {% if var1 >= var2%}
        <p><i>var1 è maggiore o uguale di var2 </i></p>
    {% elif var1 < var1 %}
        <p><i>var1 è minore di var2 </i></p>
    {% endif %}
    {% if var1 == var2 %}
        <p><i>var1 è uguale a var2 </i></p>
    {% elif var1 != var2%}
        <p><i>var1 non è uguale a var2 </i></p>
    {% endif %}
    {% if var1 < var2 and var1 < var3 %}
        <p><i>var1 è minore di var2 and var1 è minore di var3 </i></p>
    {% elif var1 > var2 and var1 > var3%}
        <p><i>var1 è maggiore di var2 and var1 è maggiore di var3 </i></p>
    {% endif %}
    {% if not var1 > var2%}
        <p><i>var1 non è maggiore di var2 </i></p>
    {% elif not var1 < var2%}
        <p><i>var1 non è minore di var2 </i></p>
    {% else %}
        <p><i>var1 è uguale a var2 </i></p>
    {% endif %}
{%endblock content%}

seconda_app/templates/seconda_app/index.html
{% extends "base.html"%}
{% block title%} {{block.super}} | Index {% endblock title%}

{%block content%}
    <ol>
        <li><a href="{% url 'seconda_app:es_if'%}">Esempio If</a></li>
        <li><a href="{% url 'seconda_app:if_else_elif'%}">Esempio If Else e Elif</a></li>
        <li><a href="{% url 'seconda_app:es_for'%}">Esempio for</a></li>
    </ol>
{%endblock content%}

                        
                       
                        

templates/base.html
<!doctype html>
{% load static %}
<!-- Questo consente di caricare un tag(static) che ha il compito di 
 aggiungere dinamicamente i link alle risorse(es. css) -->
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>{% block title %} Primo progetto {% endblock title %}</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="/">Primo progetto</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <!-- Dropdown prima app-->
                    <a class="nav-link dropdown-toggle" href="#" id="primaAppDropdownMenuLink" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Prima App
                    </a>
                    <div class="dropdown-menu" aria-labelledby="primaAppDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'prima_app:index'%}">Index</a>
                        <a class="dropdown-item" href="{% url 'prima_app:homepage'%}">Home page benvenuto</a>
                        <a class="dropdown-item" href="{% url 'prima_app:chi_siamo'%}">Chi siamo</a>
                        <a class="dropdown-item" href="{% url 'prima_app:welcome'%}">Welcome</a>
                        <a class="dropdown-item" href="{% url 'prima_app:lista'%}">Lista</a>
                        <a class="dropdown-item" href="{% url 'prima_app:variabili'%}">Variabili</a>
                      
                    </div>
                </li>

                <li class="nav-item dropdown">
                    <!-- Dropdown seconda app-->
                    <a class="nav-link dropdown-toggle" href="#" id="secondaAppDropdownMenuLink" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Seconda App
                    </a>
                    <div class="dropdown-menu" aria-labelledby="secondaAppDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'seconda_app:index'%}">Index</a>
                        <a class="dropdown-item" href="{% url 'seconda_app:es_if'%}">Esempio If</a>
                        <a class="dropdown-item" href="{% url 'seconda_app:if_else_elif'%}">Esempio If Else e Elif</a>
                        <a class="dropdown-item" href="{% url 'seconda_app:es_for'%}">Esempio for</a>
                         
                    </div>

                     <li class="nav-item dropdown">
                    <!-- Dropdown terza_app app-->
                    <a class="nav-link dropdown-toggle" href="#" id="secondaAppDropdownMenuLink" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        terza_app
                    </a>
                    <div class="dropdown-menu" aria-labelledby="terzaAppDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'terza_app:diff'%}">differenza</a>
                        <a class="dropdown-item" href="{% url 'terza_app:pari'%}">pari</a>
                         
                         
                    </div>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container my-4">
        {%block content%}
        {%endblock content%}

        {%block script%}
        {%endblock script%}
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->

</body>

</html>

templates/index_root.html
{% extends "base.html"%}
{% block title%} {{block.super}} | indice root {% endblock title%}

{%block content%}
    <ol>
        <li><a href="/admin">Pannello admin</a></li>
        <li><a href="{% url 'prima_app:index'%}">indice prima app</a></li>
        <li><a href="{% url 'seconda_app:index'%}">indice seconda app</a></li>
    </ol>
{%endblock content%}

terza_app/templates/terza_app/diff.html
{% extends "base.html.html"%}
{% block title%} {{block.super}} | differenza {% endblock title%}

{%block content%}
    <b>var1 = {{ n1 }} </b> <br/>
    <b>var2 = {{ n2 }}</b> <br/>
    <b>var3 = {{ diff }}</b> <br/>
    {% if n1 < n2 %}
        <p > il numero n2 è il più piccolo </i> </b>
    {% elif n1 > n2 %}
        <p><i>il numero n1 è il più graqnde</i></b>
        <p><i>il numero n2 è il più piccolo</i></b>
    {% else %}
        <p><i>var1 è uguale a var2 </i></b>
    {% endif %}
    
     

    
{%endblock content%}

terza_app/templates/terza_app/index.html
{% extends "base.html"%}
{% block title%} {{block.super}} | Index {% endblock title%}

{%block content%}
    <ol>
        <li><a href="{% url 'terza_app:diff'%}">differenza</a></li>
        <li><a href="{% url 'terza_app:pari'%}">pari</a></li>
        
    </ol>
{%endblock content%}

terza_app/templates/terza_app/pari.html
{% extends "base.html"%}
{% block title%} {{block.super}} | pari {% endblock title%}

{%block content%}
     
    <b>var1 = {{ n1 }} </b> <br/>
    <b>var2 = {{ n2 }} </b> <br/>
    <b>var2 = {{ n3 }} </b> <br/>
    <br/>
    {% for x in list2 %}
    <i>{{ forloop.counter }} </i>: {{ x }}<br>
    {% if numero|divisibleby:2 %}
     <p> il numero è pari</p>
       {% endif %}


    {% endfor %}
    {%endblock content%}